config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'topics/index'
  get 'topics/show'
  devise_for :users
  root to: "pages#home"

  resources :topics, only: [:index, :show] do
    resources :chats, only: [:create]
  end

  resources :chats, only: [:show] do
    resources :messages, only: [:create]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :chats, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @chats = @topic.chats.where(user: current_user)
  end
end

app/views/topics/index.html.erb
<div class="container py-4">
  <h1>Topics</h1>

  <ul>
    <% @topics.each do |topic| %>
      <li><%= link_to topic.name, topic_path(topic) %></li>
    <% end %>
  </ul>
</div>

app/views/topics/show.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col">
      <h1><%= @topic.name %></h1>
      <p><%= @topic.content %></p>
    </div>

    <div class="col-md-4">
      <h2>Chats</h2>

      <% if @chats.any? %>
        <ul>
          <% @chats.each do |chat| %>
            <li><%= link_to chat.title, chat_path(chat) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no chats yet.</p>
      <% end %>

      <%= button_to "New chat", topic_chats_path(@topic), class: "btn btn-primary mt-3" %>
    </div>
  </div>
</div>